import initTabNav from './modules/tabnav.js';
import initScrollSuave from './modules/scroll-suave.js';
import initAccordion from './modules/accordion.js';
import animacaoScroll from './modules/anima-scroll.js';
import initModal from './modules/modal.js';
import initTooltip from './modules/tooltip.js';
import initDropdownMenu from './modules/dropdown-menu.js';
import initMenuMobile from './modules/menumobile.js';
import initAnimaNumeros from './modules/anima-numeros.js';
import initFuncionamento from './modules/funcionamento.js';

initTabNav();
initScrollSuave();
initAccordion();
animacaoScroll();
initModal();
initTooltip();
initDropdownMenu();
initMenuMobile();
initAnimaNumeros();
initFuncionamento();